version: 2.0
workflows:
  main:
   jobs:
    build:
      docker:
        - image: cibuilds/docker:19.03
        - run:
           name: "Build Docker Image"
           command: docker build --file Dockerfile
      


