version: 2.0

jobs:
  build:
    docker:
      - image: cibuilds/docker:19.03
    steps:
      - checkout
      - setup_docker_php
      - run:
          name: "Build Docker Image"
          command: docker build --file Dockerfile
      - deploy:
          name: "Publish Docker Images (master branch only)"
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              
              echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
              
              # an else block will be added in the future for a staging release
              if git log -1 --pretty=%s | grep "\[release\]"; then
                echo "Publishing gitpress/wp to Docker Hub production."
                docker push gitpress/wp
              else
                echo "Skipping publishing."
            fi    


